// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesEcommerceBlazor.Server.Data;

#nullable disable

namespace MoviesEcommerceBlazor.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220612212401_ProductsInDb")]
    partial class ProductsInDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MoviesEcommerceBlazor.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "In this third globe-trotting screen adventure of Dan Brown's indefatigable iconologist Prof. Robert Langdon (Tom Hanks)-and another partnering for the star and director Ron Howard-a demented entrepreneur (Ben Foster) has decided to combat global overpopulation by unleashing a killer virus, and Langdon must unravel the madman's skein of Dante-themed clues to in order to find the doomsday weapon. Potent thriller co-stars Felicity Jones, Sidse Babett Knudsen, Irrfan Khan, Omar Sy. 4K Ultra HD includes bonus DVD on 2 Discs. Directed by Ron Howard. 2016 / color / 122 min / PG-13 / widescreen.",
                            ImageUrl = "https://aentcdn.azureedge.net/graphics/items/sdimages/c/300/8/7/0/1/3471078.jpg?ae=2309403150",
                            Price = 9.99m,
                            Title = "Inferno (2016)"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Still struggling with his physical and emotional battle scars, but desperate for reinstatement, ex-Army Ranger Jackson Briggs (Channing Tatum, who co-directed) would do anything to prove himself. So, he agreed to drive another troubled veteran--Belgian Malinois service dog Lulu--from Oregon to Arizona for the funeral of her handler. The mutual wariness gives way to a warm bond during this comically calamitous road trip. Ethan Suplee, Q’orianka Kilcher, Emmy Raver-Lampman, Bill Burr co-star. 101 min. Widescreen; Soundtrack: English.",
                            ImageUrl = "https://mediacdn.aent-m.com/prod-img/300/50/4075150-2823623.jpg?ae=2309403150",
                            Price = 8.99m,
                            Title = "Dog (2022)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "As a boy, the Viking prince Amleth bore witness to the slaying of his father Aurvandill (Ethan Hawke) by his treacherous uncle Fjölnir (Claes Bang), who'd desired his mother Gudrún (Nicole Kidman). Having fled for his life, he swore he'd have vengeance--and the day came that Amleth (Alexander Skarsgård), grown into a formidable barbarian, returned to claim it. Robert Eggers' brooding, brutal take on the mythos that inspired Hamlet co-stars Anya Taylor-Joy, Willem Defoe, Björk. 136 min. Widescreen; Soundtrack: English.",
                            ImageUrl = "https://mediacdn.aent-m.com/prod-img/300/00/4085200-2835918.jpg?ae=2309403150",
                            Price = 11.99m,
                            Title = "The Northman (2022)"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
